// This file will be auto-generated by: pnpm db:types
// For now, provide a placeholder type
export type Database = {
  public: {
    Tables: {
      tenants: {
        Row: {
          id: string;
          name: string;
          slug: string;
          plan: string;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["tenants"]["Row"], "id" | "created_at" | "updated_at"> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["tenants"]["Insert"]>;
      };
      members: {
        Row: {
          id: string;
          tenant_id: string;
          line_user_id: string;
          display_name: string;
          picture_url: string | null;
          rank: string;
          total_points: number;
          visit_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["members"]["Row"], "id" | "created_at" | "updated_at"> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["members"]["Insert"]>;
      };
      point_transactions: {
        Row: {
          id: string;
          member_id: string;
          tenant_id: string;
          amount: number;
          balance_after: number;
          type: string;
          description: string | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["point_transactions"]["Row"], "id" | "created_at"> & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["point_transactions"]["Insert"]>;
      };
      coupons: {
        Row: {
          id: string;
          tenant_id: string;
          title: string;
          description: string | null;
          discount_type: string;
          discount_value: number;
          min_purchase: number | null;
          is_active: boolean;
          max_uses: number | null;
          used_count: number;
          expires_at: string | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["coupons"]["Row"], "id" | "created_at" | "used_count"> & {
          id?: string;
          created_at?: string;
          used_count?: number;
        };
        Update: Partial<Database["public"]["Tables"]["coupons"]["Insert"]>;
      };
      coupon_uses: {
        Row: {
          id: string;
          coupon_id: string;
          member_id: string;
          tenant_id: string;
          used_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["coupon_uses"]["Row"], "id" | "used_at"> & {
          id?: string;
          used_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["coupon_uses"]["Insert"]>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
