// This file will be auto-generated by: pnpm db:types
// For now, provide a placeholder type

// ---------- Row types ----------
type TenantRow = {
  id: string;
  name: string;
  slug: string;
  plan: string;
  status: string;
  created_at: string;
  updated_at: string;
};

type MemberRow = {
  id: string;
  tenant_id: string;
  line_user_id: string;
  auth_user_id: string | null;
  display_name: string;
  picture_url: string | null;
  rank: string;
  total_points: number;
  visit_count: number;
  created_at: string;
  updated_at: string;
};

type PointTransactionRow = {
  id: string;
  member_id: string;
  tenant_id: string;
  amount: number;
  balance_after: number;
  type: string;
  description: string | null;
  created_at: string;
};

type CouponRow = {
  id: string;
  tenant_id: string;
  title: string;
  description: string | null;
  discount_type: string;
  discount_value: number;
  min_purchase: number | null;
  is_active: boolean;
  max_uses: number | null;
  used_count: number;
  expires_at: string | null;
  created_at: string;
};

type CouponUseRow = {
  id: string;
  coupon_id: string;
  member_id: string;
  tenant_id: string;
  used_at: string;
};

// ---------- Database type ----------
export type Database = {
  public: {
    Tables: {
      tenants: {
        Row: TenantRow;
        Insert: Omit<TenantRow, "id" | "created_at" | "updated_at"> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<
          Omit<TenantRow, "id" | "created_at" | "updated_at"> & {
            id?: string;
            created_at?: string;
            updated_at?: string;
          }
        >;
        Relationships: [];
      };
      members: {
        Row: MemberRow;
        Insert: Omit<MemberRow, "id" | "auth_user_id" | "created_at" | "updated_at"> & {
          id?: string;
          auth_user_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<
          Omit<MemberRow, "id" | "auth_user_id" | "created_at" | "updated_at"> & {
            id?: string;
            auth_user_id?: string | null;
            created_at?: string;
            updated_at?: string;
          }
        >;
        Relationships: [
          {
            foreignKeyName: "members_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
        ];
      };
      point_transactions: {
        Row: PointTransactionRow;
        Insert: Omit<PointTransactionRow, "id" | "created_at"> & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<
          Omit<PointTransactionRow, "id" | "created_at"> & {
            id?: string;
            created_at?: string;
          }
        >;
        Relationships: [
          {
            foreignKeyName: "point_transactions_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "point_transactions_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
        ];
      };
      coupons: {
        Row: CouponRow;
        Insert: Omit<CouponRow, "id" | "created_at" | "used_count"> & {
          id?: string;
          created_at?: string;
          used_count?: number;
        };
        Update: Partial<
          Omit<CouponRow, "id" | "created_at" | "used_count"> & {
            id?: string;
            created_at?: string;
            used_count?: number;
          }
        >;
        Relationships: [
          {
            foreignKeyName: "coupons_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
        ];
      };
      coupon_uses: {
        Row: CouponUseRow;
        Insert: Omit<CouponUseRow, "id" | "used_at"> & {
          id?: string;
          used_at?: string;
        };
        Update: Partial<
          Omit<CouponUseRow, "id" | "used_at"> & {
            id?: string;
            used_at?: string;
          }
        >;
        Relationships: [
          {
            foreignKeyName: "coupon_uses_coupon_id_fkey";
            columns: ["coupon_id"];
            isOneToOne: false;
            referencedRelation: "coupons";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "coupon_uses_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "coupon_uses_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: {
      use_coupon: {
        Args: {
          p_coupon_id: string;
          p_member_id: string;
          p_tenant_id: string;
        };
        Returns: {
          ok: boolean;
          data?: { usedAt: string };
          error?: string;
        };
      };
      earn_points: {
        Args: {
          p_member_id: string;
          p_tenant_id: string;
          p_amount: number;
          p_description?: string | null;
        };
        Returns: {
          ok: boolean;
          data?: {
            transactionId: string;
            amount: number;
            newBalance: number;
          };
          error?: string;
        };
      };
    };
    Enums: Record<string, never>;
  };
};
